BASIC-UI
Nowembabazi/OPP_SCH_LIBRARY pull request #4
Opened 2023-01-18 19:09 UTC by Nowembabazi

##In this milestone I achieved the following;
-Perfect workflow.
-Created an app.rb file.
-Followed the best practises of ruby.

2023-01-18 19:31 UTC, Deepakdanger requested changes
Hi @Nowembabazi , 

Good job so far! 👏
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight :100: 
- No linter error :heavy_check_mark: 
- Website looks professional :+1: 

## Required Changes ♻️
- [ ] While creating person(student or teacher ), getting some argument error in initialisation.Plz correct it.
![Screenshot from 2023-01-19 00-49-21](https://user-images.githubusercontent.com/26767383/213276512-9d7bd742-b9b2-44bd-ad5b-5472fe9f964f.png)

![Screenshot from 2023-01-19 00-49-52](https://user-images.githubusercontent.com/26767383/213276544-8e7a95ce-424f-4175-9456-870049496f30.png)


- NOTE:- I can't able to check the rental part as `person` is not created, plz check the rental part from your end before submitting it for the next review.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-19 07:59 UTC, zieeco requested changes
Hi @Nowembabazi ,


Great work on making the changes requested by the previous reviewer 👏 
You've done well implementing some of the changes, however, there are some issues that you still need to work on to go to the next project, but you are almost there!


## To highlight 🎯

- No linter errors.✔️
- Nice app. ✔️
- Descriptive PR. ✔️


## Required Changes ♻️
_Check the comments under the review._


<img src="https://media0.giphy.com/media/8UGVQESpDMMQl7yd3F/giphy.gif"/>


## Optional suggestions
- N/A

**_Every comment with the **[OPTIONAL]** prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._**


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-19 07:59 UTC, zieeco commented on create_teacher.rb
> +end
- Great job addressing the issue pointed out by the previous reviewer, however, I can't create a teacher successfully. Please, kindly fix this issue of the argument below:


![Screenshot from 2023-01-19 08-45-56](https://user-images.githubusercontent.com/59397159/213385671-d635850a-eda4-467c-9617-f26b941e588b.png)

2023-01-19 07:59 UTC, zieeco commented on create_student.rb
> +end
- For the student, I don't seem to be able to create a student also. Please, fix the argument error it throws from the terminal below:


![Screenshot from 2023-01-19 08-56-17](https://user-images.githubusercontent.com/59397159/213386174-a680a838-a1d5-4960-9e64-fefc56bb80e4.png)

2023-01-19 09:18 UTC, TedLivist requested changes
## STATUS: CHANGES REQUIRED ♻️ ♻️

Hi @Nowembabazi,

✔️ Suggestion of option when listing books and people

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-19 09:18 UTC, TedLivist commented on rental.rb
>    end
- [ ] When I try to create a rental I get this error message (see image). You can fix this by changing this `initialize` method to this as it was:

  ```
  def initialize(date, person, book)
    @date = date
    @person = person
    @book = book

    person.rentals << self
    book.rentals << self
  end
  ```

  ![image](https://user-images.githubusercontent.com/36542986/213402725-deb82e12-f2d7-4b88-98b6-3adf3913bfcf.png)

2023-01-19 09:51 UTC, TedLivist approved these changes
## STATUS: APPROVED ✔️ ✔️

Hi @Nowembabazi,

✔️ Implementation of rental creation

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-19 10:25 UTC, merged